name: argeazy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_solidart: ^1.7.1
  flutter_dotenv: ^5.1.0
  http:
  shadcn_ui: ^0.8.0
  file_picker: ^8.1.2
  shared_preferences:
  google_translate:

dev_dependencies:
  flutter_test:
    sdk: flutter
  get:
  flutter_svg:
  flutter_lints: ^3.0.0
  change_app_package_name: ^1.3.0
  flutter_launcher_icons: 

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/images/
